_extends: .github

repository:
  name: node-install-group
  description: Dependency grouping for npm-install
  topics: npm,install,group
  homepage: https://github.com/ahmadnassri/node-install-group
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
